export const dynamic = 'force-dynamic';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/components/providers/QueryClientProvider';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { TooltipProvider } from '@/components/ui/tooltip';
import ToasterProvider from '@/components/providers/ToastProvider';
import { Toaster } from '@/components/ui/toaster';
import RouteLoadingProvider from '@/components/providers/RouteLoadingProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});
const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: '典藏網站後台',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="zh-TW" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <QueryProvider>
                    <ThemeProvider defaultTheme="light">
                        <TooltipProvider>
                            <ToasterProvider />
                            <Toaster />
                            <RouteLoadingProvider>
                                {children}
                            </RouteLoadingProvider>
                        </TooltipProvider>
                    </ThemeProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
